spring:
  application:
    name: syncora-api
  profiles:
    active: dev
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
