spring:
  application:
    name: syncora-api
  profiles:
    active: prod

server:
  port: 8080
# Actuator : expose all endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

#swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha

#Jackson : pretty-print
jackson:
  serialization:
    indent_output: true

logging:
  level:
    root: info
