spring:
  datasource:
    #url: jdbc:postgresql://nxhngcimpovjdutttsvz.supabase.co:5432/postgres
#    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
    username: postgres.nxhngcimpovjdutttsvz
    password: ${DB_PASSWORD}
#    pool_mode: session
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      isolate-internal-queries: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jackson:
  serialization:
    indent_output: false

logging:
  level:
    org.springframework: info
#    org.zaxxer.hikari: debug

